// <auto-generated />
using System;
using Innovatek.Parallel.MiniCluster.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Innovatek.Parallel.MiniCluster.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260110185522_AddProxyRoutes")]
    partial class AddProxyRoutes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("Innovatek.ControlCenter.Core.Entities.AppFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AppId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AppFiles");
                });

            modelBuilder.Entity("Innovatek.ControlCenter.Core.Entities.AppSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableLogSearch")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxMessagesToKeepInUi")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MetricsAggregationIntervalSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MetricsCollectionIntervalSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MetricsRetentionHours")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AppSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EnableLogSearch = true,
                            MaxMessagesToKeepInUi = 1000,
                            MetricsAggregationIntervalSeconds = 60,
                            MetricsCollectionIntervalSeconds = 5,
                            MetricsRetentionHours = 24,
                            ModifiedAt = new DateTime(2026, 1, 10, 18, 55, 19, 719, DateTimeKind.Utc).AddTicks(8407)
                        });
                });

            modelBuilder.Entity("Innovatek.ControlCenter.Core.Entities.ControlledApp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccessLink")
                        .HasColumnType("TEXT");

                    b.Property<string>("Arguments")
                        .HasColumnType("TEXT");

                    b.Property<bool>("AutoStart")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CaptureOutput")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CreateNoWindow")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EnvironmentVariables")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecutablePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsExternal")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("UseShellExecute")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WorkingDirectory")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AutoStart");

                    b.HasIndex("Name");

                    b.ToTable("ControlledApps");
                });

            modelBuilder.Entity("Innovatek.ControlCenter.Core.Entities.ProxyRoute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AllowedRoles")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomHeaders")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EnableIframe")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnablePathPrefix")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnablePort")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableSubdomain")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Icon")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHealthy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastHealthCheck")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PathPrefix")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PreserveHostHeader")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProxyPort")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RequireAuth")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RewriteUrls")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RewriteWebSocket")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("StripXFrameOptions")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Subdomain")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TimeoutSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsEnabled");

                    b.HasIndex("PathPrefix")
                        .IsUnique();

                    b.HasIndex("ProxyPort")
                        .IsUnique();

                    b.HasIndex("Subdomain")
                        .IsUnique();

                    b.ToTable("ProxyRoutes");
                });

            modelBuilder.Entity("Innovatek.ControlCenter.Core.Entities.ProxySettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BaseDomainType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomBaseDomain")
                        .HasColumnType("TEXT");

                    b.Property<bool>("DefaultRequireAuth")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PortRangeEnd")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PortRangeStart")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServerIp")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ProxySettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseDomainType = "nip.io",
                            DefaultRequireAuth = true,
                            PortRangeEnd = 5099,
                            PortRangeStart = 5001,
                            UpdatedAt = new DateTime(2026, 1, 10, 18, 55, 19, 735, DateTimeKind.Utc).AddTicks(1720)
                        });
                });

            modelBuilder.Entity("Innovatek.ControlCenter.Core.Entities.VariableGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Variables")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("VariableGroups");
                });
#pragma warning restore 612, 618
        }
    }
}
