// <auto-generated />
using System;
using Innovatek.Parallel.MiniCluster.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Innovatek.Parallel.MiniCluster.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260130072321_AddMachinesServicesAndGroups")]
    partial class AddMachinesServicesAndGroups
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("Innovatek.ControlCenter.Core.Entities.AppFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AppId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AppFiles");
                });

            modelBuilder.Entity("Innovatek.ControlCenter.Core.Entities.AppGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ParentGroupId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("ParentGroupId");

                    b.ToTable("AppGroups");
                });

            modelBuilder.Entity("Innovatek.ControlCenter.Core.Entities.AppGroupAssignment", b =>
                {
                    b.Property<Guid>("AppId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("AppId", "GroupId");

                    b.HasIndex("GroupId");

                    b.ToTable("AppGroupAssignments");
                });

            modelBuilder.Entity("Innovatek.ControlCenter.Core.Entities.AppSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableLogSearch")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxMessagesToKeepInUi")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MetricsAggregationIntervalSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MetricsCollectionIntervalSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MetricsRetentionHours")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AppSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EnableLogSearch = true,
                            MaxMessagesToKeepInUi = 1000,
                            MetricsAggregationIntervalSeconds = 60,
                            MetricsCollectionIntervalSeconds = 5,
                            MetricsRetentionHours = 24,
                            ModifiedAt = new DateTime(2026, 1, 30, 7, 23, 19, 16, DateTimeKind.Utc).AddTicks(7842)
                        });
                });

            modelBuilder.Entity("Innovatek.ControlCenter.Core.Entities.ControlledApp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccessLink")
                        .HasColumnType("TEXT");

                    b.Property<string>("Arguments")
                        .HasColumnType("TEXT");

                    b.Property<bool>("AutoStart")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CaptureOutput")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CreateNoWindow")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("EnvironmentVariables")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecutablePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsComposite")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsExternal")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ParentAppId")
                        .HasColumnType("TEXT");

                    b.Property<string>("StartMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("UseShellExecute")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WorkingDirectory")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AutoStart");

                    b.HasIndex("IsComposite");

                    b.HasIndex("Name");

                    b.HasIndex("ParentAppId");

                    b.ToTable("ControlledApps");
                });

            modelBuilder.Entity("Innovatek.ControlCenter.Core.Entities.GroupVariable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSecret")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("GroupId", "Key")
                        .IsUnique();

                    b.ToTable("GroupVariables");
                });

            modelBuilder.Entity("Innovatek.ControlCenter.Core.Entities.Machine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConnectionType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Host")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsLocal")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastSeen")
                        .HasColumnType("TEXT");

                    b.Property<string>("Metadata")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SshKeyPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("SshPassword")
                        .HasColumnType("TEXT");

                    b.Property<string>("SshUsername")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Host");

                    b.HasIndex("IsLocal");

                    b.HasIndex("Name");

                    b.HasIndex("Status");

                    b.ToTable("Machines");
                });

            modelBuilder.Entity("Innovatek.ControlCenter.Core.Entities.ProxyRoute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AllowedRoles")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiKey")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomHeaders")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EnableIframe")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnablePathPrefix")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnablePort")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableSubdomain")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Icon")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHealthy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastHealthCheck")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PathPrefix")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PreserveHostHeader")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProxyPort")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RequireAuth")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RewriteUrls")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RewriteWebSocket")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("StripXFrameOptions")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Subdomain")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TimeoutSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsEnabled");

                    b.HasIndex("PathPrefix")
                        .IsUnique();

                    b.HasIndex("ProxyPort")
                        .IsUnique();

                    b.HasIndex("Subdomain")
                        .IsUnique();

                    b.ToTable("ProxyRoutes");
                });

            modelBuilder.Entity("Innovatek.ControlCenter.Core.Entities.ProxySettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BaseDomainType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomBaseDomain")
                        .HasColumnType("TEXT");

                    b.Property<bool>("DefaultRequireAuth")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PortRangeEnd")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PortRangeStart")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServerIp")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ProxySettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseDomainType = "nip.io",
                            DefaultRequireAuth = true,
                            PortRangeEnd = 5099,
                            PortRangeStart = 5001,
                            UpdatedAt = new DateTime(2026, 1, 30, 7, 23, 19, 29, DateTimeKind.Utc).AddTicks(2068)
                        });
                });

            modelBuilder.Entity("Innovatek.ControlCenter.Core.Entities.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccessLink")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AppId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Arguments")
                        .HasColumnType("TEXT");

                    b.Property<bool>("AutoStart")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CaptureOutput")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContainerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContainerName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("CreateNoWindow")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DockerOptions")
                        .HasColumnType("TEXT");

                    b.Property<string>("EnvironmentVariables")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecutablePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.Property<bool>("InheritEnvFromApp")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsExternal")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("MachineId")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxRestartAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Network")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ports")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProcessId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RestartOnFailure")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StartOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseShellExecute")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Volumes")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkingDirectory")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AppId");

                    b.HasIndex("MachineId");

                    b.HasIndex("Name");

                    b.HasIndex("Status");

                    b.HasIndex("Type");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("Innovatek.ControlCenter.Core.Entities.VariableGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Variables")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("VariableGroups");
                });

            modelBuilder.Entity("Innovatek.ControlCenter.Core.Entities.AppGroup", b =>
                {
                    b.HasOne("Innovatek.ControlCenter.Core.Entities.AppGroup", "ParentGroup")
                        .WithMany("ChildGroups")
                        .HasForeignKey("ParentGroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentGroup");
                });

            modelBuilder.Entity("Innovatek.ControlCenter.Core.Entities.AppGroupAssignment", b =>
                {
                    b.HasOne("Innovatek.ControlCenter.Core.Entities.ControlledApp", "App")
                        .WithMany("GroupAssignments")
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Innovatek.ControlCenter.Core.Entities.AppGroup", "Group")
                        .WithMany("AppAssignments")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("App");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Innovatek.ControlCenter.Core.Entities.ControlledApp", b =>
                {
                    b.HasOne("Innovatek.ControlCenter.Core.Entities.ControlledApp", "ParentApp")
                        .WithMany("ChildApps")
                        .HasForeignKey("ParentAppId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentApp");
                });

            modelBuilder.Entity("Innovatek.ControlCenter.Core.Entities.GroupVariable", b =>
                {
                    b.HasOne("Innovatek.ControlCenter.Core.Entities.AppGroup", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Innovatek.ControlCenter.Core.Entities.Service", b =>
                {
                    b.HasOne("Innovatek.ControlCenter.Core.Entities.ControlledApp", "App")
                        .WithMany("Services")
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Innovatek.ControlCenter.Core.Entities.Machine", "Machine")
                        .WithMany("Services")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("App");

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("Innovatek.ControlCenter.Core.Entities.AppGroup", b =>
                {
                    b.Navigation("AppAssignments");

                    b.Navigation("ChildGroups");
                });

            modelBuilder.Entity("Innovatek.ControlCenter.Core.Entities.ControlledApp", b =>
                {
                    b.Navigation("ChildApps");

                    b.Navigation("GroupAssignments");

                    b.Navigation("Services");
                });

            modelBuilder.Entity("Innovatek.ControlCenter.Core.Entities.Machine", b =>
                {
                    b.Navigation("Services");
                });
#pragma warning restore 612, 618
        }
    }
}
