// <auto-generated />
using System;
using Innovatek.Parallel.MiniCluster.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Innovatek.Parallel.MiniCluster.Api.Migrations
{
    [DbContext(typeof(LogsDbContext))]
    [Migration("20260102031939_InitialLogsDbSchema")]
    partial class InitialLogsDbSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("Innovatek.ControlCenter.Core.Entities.AppLifecycleEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AppId")
                        .HasColumnType("TEXT");

                    b.Property<int>("EventType")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ExitCode")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("TriggeredBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AppId");

                    b.HasIndex("Timestamp");

                    b.HasIndex("AppId", "Timestamp");

                    b.ToTable("LifecycleEvents");
                });

            modelBuilder.Entity("Innovatek.ControlCenter.Core.Entities.AppSession", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AppId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("AutoStart")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CommandLineArguments")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("EnvironmentSnapshot")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ExitCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExitReason")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkingDirectory")
                        .HasColumnType("TEXT");

                    b.HasKey("SessionId");

                    b.HasIndex("AppId");

                    b.HasIndex("StartTimestamp");

                    b.HasIndex("AppId", "StartTimestamp");

                    b.ToTable("AppSessions");
                });

            modelBuilder.Entity("Innovatek.ControlCenter.Core.Entities.SessionLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Line")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LogType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.HasIndex("Timestamp");

                    b.ToTable("SessionLogs");
                });

            modelBuilder.Entity("Innovatek.ControlCenter.Core.Entities.SessionLogEntry", b =>
                {
                    b.HasOne("Innovatek.ControlCenter.Core.Entities.AppSession", "AppSession")
                        .WithMany("LogEntries")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppSession");
                });

            modelBuilder.Entity("Innovatek.ControlCenter.Core.Entities.AppSession", b =>
                {
                    b.Navigation("LogEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
