// <auto-generated />
using System;
using Innovatek.Parallel.MiniCluster.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Innovatek.Parallel.MiniCluster.Api.Migrations
{
    [DbContext(typeof(LogsDbContext))]
    [Migration("20260105052150_AddProcessMetricsTables")]
    partial class AddProcessMetricsTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("Innovatek.ControlCenter.Core.Entities.AppLifecycleEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AppId")
                        .HasColumnType("TEXT");

                    b.Property<int>("EventType")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ExitCode")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("TriggeredBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AppId");

                    b.HasIndex("Timestamp");

                    b.HasIndex("AppId", "Timestamp");

                    b.ToTable("LifecycleEvents");
                });

            modelBuilder.Entity("Innovatek.ControlCenter.Core.Entities.AppSession", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AppId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("AutoStart")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CommandLineArguments")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("EnvironmentSnapshot")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ExitCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExitReason")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkingDirectory")
                        .HasColumnType("TEXT");

                    b.HasKey("SessionId");

                    b.HasIndex("AppId");

                    b.HasIndex("StartTimestamp");

                    b.HasIndex("AppId", "StartTimestamp");

                    b.ToTable("AppSessions");
                });

            modelBuilder.Entity("Innovatek.ControlCenter.Core.Entities.ProcessMetrics", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("AppId")
                        .HasColumnType("TEXT");

                    b.Property<double>("CpuUsagePercent")
                        .HasColumnType("REAL");

                    b.Property<int>("HandleCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsResponding")
                        .HasColumnType("INTEGER");

                    b.Property<long>("NetworkBytesReceived")
                        .HasColumnType("INTEGER");

                    b.Property<long>("NetworkBytesSent")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PeakWorkingSetMemory")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PrivateMemory")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProcessId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ThreadCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<long>("TotalProcessorTime")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UserProcessorTime")
                        .HasColumnType("INTEGER");

                    b.Property<long>("VirtualMemory")
                        .HasColumnType("INTEGER");

                    b.Property<long>("WorkingSetMemory")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AppId");

                    b.HasIndex("SessionId");

                    b.HasIndex("Timestamp");

                    b.HasIndex("AppId", "Timestamp");

                    b.ToTable("ProcessMetrics");
                });

            modelBuilder.Entity("Innovatek.ControlCenter.Core.Entities.ProcessMetricsAggregated", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("AppId")
                        .HasColumnType("TEXT");

                    b.Property<double>("AvgCpuUsagePercent")
                        .HasColumnType("REAL");

                    b.Property<double>("AvgHandleCount")
                        .HasColumnType("REAL");

                    b.Property<long>("AvgPrivateMemory")
                        .HasColumnType("INTEGER");

                    b.Property<double>("AvgThreadCount")
                        .HasColumnType("REAL");

                    b.Property<long>("AvgWorkingSetMemory")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IntervalSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MaxCpuUsagePercent")
                        .HasColumnType("REAL");

                    b.Property<int>("MaxHandleCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MaxPrivateMemory")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxThreadCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MaxWorkingSetMemory")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MinCpuUsagePercent")
                        .HasColumnType("REAL");

                    b.Property<long>("MinWorkingSetMemory")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SampleCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<long>("TotalNetworkBytesReceived")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalNetworkBytesSent")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AppId");

                    b.HasIndex("IntervalSeconds");

                    b.HasIndex("Timestamp");

                    b.HasIndex("AppId", "Timestamp", "IntervalSeconds");

                    b.ToTable("ProcessMetricsAggregated");
                });

            modelBuilder.Entity("Innovatek.ControlCenter.Core.Entities.SessionLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Line")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LogType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.HasIndex("Timestamp");

                    b.ToTable("SessionLogs");
                });

            modelBuilder.Entity("Innovatek.ControlCenter.Core.Entities.SessionLogEntry", b =>
                {
                    b.HasOne("Innovatek.ControlCenter.Core.Entities.AppSession", "AppSession")
                        .WithMany("LogEntries")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppSession");
                });

            modelBuilder.Entity("Innovatek.ControlCenter.Core.Entities.AppSession", b =>
                {
                    b.Navigation("LogEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
