// <auto-generated />
using System;
using Innovatek.Parallel.MiniCluster.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Innovatek.Parallel.MiniCluster.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Innovatek.Parallel.MiniCluster.Core.Entities.AlertRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("AppId")
                        .HasColumnType("TEXT");

                    b.Property<int>("CooldownMinutes")
                        .HasDefaultValue(5)
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationSeconds")
                        .HasDefaultValue(0)
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasDefaultValue(true)
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastTriggeredAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Metric")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("NotifyChannels")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasDefaultValue("all")
                        .HasColumnType("TEXT");

                    b.Property<int>("Operator")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ServiceId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Threshold")
                        .HasColumnType("REAL");

                    b.Property<int>("TriggerCount")
                        .HasDefaultValue(0)
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IsEnabled");

                    b.ToTable("AlertRules");
                });

            modelBuilder.Entity("Innovatek.Parallel.MiniCluster.Core.Entities.AlertEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AlertRuleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EventType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT");

                    b.Property<string>("NotificationResults")
                        .HasColumnType("TEXT");

                    b.Property<double>("Threshold")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<double>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("AlertRuleId");

                    b.HasIndex("Timestamp");

                    b.ToTable("AlertEvents");
                });

            modelBuilder.Entity("Innovatek.Parallel.MiniCluster.Core.Entities.NotificationChannel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailSubjectTemplate")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailTo")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasDefaultValue(true)
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WebhookHeaders")
                        .HasColumnType("TEXT");

                    b.Property<string>("WebhookTemplate")
                        .HasColumnType("TEXT");

                    b.Property<string>("WebhookUrl")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsEnabled");

                    b.ToTable("NotificationChannels");
                });

            modelBuilder.Entity("Innovatek.Parallel.Identity.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReplacedByToken")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Innovatek.Parallel.Identity.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Operator");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Innovatek.Parallel.MiniCluster.Core.Entities.App", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentAppId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ParentAppId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("SortOrder");

                    b.ToTable("Apps");
                });

            modelBuilder.Entity("Innovatek.Parallel.MiniCluster.Core.Entities.AppSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableLogSearch")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxMessagesToKeepInUi")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MetricsAggregationIntervalSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MetricsCollectionIntervalSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MetricsRetentionHours")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AppSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EnableLogSearch = true,
                            MaxMessagesToKeepInUi = 1000,
                            MetricsAggregationIntervalSeconds = 60,
                            MetricsCollectionIntervalSeconds = 5,
                            MetricsRetentionHours = 24,
                            ModifiedAt = new DateTime(2026, 2, 7, 12, 18, 29, 43, DateTimeKind.Utc).AddTicks(3343)
                        });
                });

            modelBuilder.Entity("Innovatek.Parallel.MiniCluster.Core.Entities.AppSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("AppId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AppId");

                    b.ToTable("AppSnapshots", (string)null);
                });

            modelBuilder.Entity("Innovatek.Parallel.MiniCluster.Core.Entities.AppSnapshotEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AppSnapshotId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ServiceVersionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AppSnapshotId");

                    b.HasIndex("ServiceVersionId");

                    b.ToTable("AppSnapshotEntries", (string)null);
                });

            modelBuilder.Entity("Innovatek.Parallel.MiniCluster.Core.Entities.ContainerConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContainerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContainerName")
                        .HasColumnType("TEXT");

                    b.Property<double?>("CpuLimit")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Hostname")
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Labels")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<long?>("MemoryLimitBytes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("NetworkMode")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PortMappings")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Privileged")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Registry")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("RestartPolicy")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("latest");

                    b.Property<string>("User")
                        .HasColumnType("TEXT");

                    b.Property<string>("VolumeMounts")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId")
                        .IsUnique();

                    b.ToTable("ContainerConfigs", (string)null);
                });

            modelBuilder.Entity("Innovatek.Parallel.MiniCluster.Core.Entities.CronJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Action")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("AppId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CronExpression")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DependsOnJobId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedRuns")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastRun")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastRunError")
                        .HasColumnType("TEXT");

                    b.Property<int>("LastRunStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MissedPolicy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NextRun")
                        .HasColumnType("TEXT");

                    b.Property<string>("ScriptPath")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ServiceId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TargetType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimeoutSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Timezone")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("UTC");

                    b.Property<int>("TotalRuns")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("WaitForCompletion")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AppId");

                    b.HasIndex("DependsOnJobId");

                    b.HasIndex("GroupId");

                    b.HasIndex("IsEnabled");

                    b.HasIndex("Name");

                    b.HasIndex("ServiceId");

                    b.ToTable("CronJobs", (string)null);
                });

            modelBuilder.Entity("Innovatek.Parallel.MiniCluster.Core.Entities.CronJobRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CronJobId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ExitCode")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("JobId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Output")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ScheduledFor")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CronJobId");

                    b.HasIndex("JobId");

                    b.HasIndex("StartedAt");

                    b.ToTable("CronJobRuns", (string)null);
                });

            modelBuilder.Entity("Innovatek.Parallel.MiniCluster.Core.Entities.DeploymentConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoRollbackOnFailure")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoVersionOnSave")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HealthCheckTimeoutSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxVersionsToKeep")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RollbackTimeoutSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Strategy")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("WaitForHealthy")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId")
                        .IsUnique();

                    b.ToTable("DeploymentConfigs", (string)null);
                });

            modelBuilder.Entity("Innovatek.Parallel.MiniCluster.Core.Entities.Environment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Variables")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Environments");
                });

            modelBuilder.Entity("Innovatek.Parallel.MiniCluster.Core.Entities.GroupVariable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSecret")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GroupId", "Key")
                        .IsUnique();

                    b.ToTable("GroupVariables");
                });

            modelBuilder.Entity("Innovatek.Parallel.MiniCluster.Core.Entities.Machine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentApiKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentEndpoint")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentVersion")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConnectionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int?>("CpuCores")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Host")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsLocal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Labels")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSeen")
                        .HasColumnType("TEXT");

                    b.Property<string>("Metadata")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SshKeyPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("SshPassword")
                        .HasColumnType("TEXT");

                    b.Property<string>("SshUsername")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<long?>("TotalDiskBytes")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TotalMemoryBytes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Host");

                    b.HasIndex("IsLocal");

                    b.HasIndex("Name");

                    b.HasIndex("Status");

                    b.ToTable("Machines");
                });

            modelBuilder.Entity("Innovatek.Parallel.MiniCluster.Core.Entities.ProxyRoute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AllowedRoles")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiKey")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomHeaders")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EnableIframe")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnablePathPrefix")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnablePort")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableSubdomain")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Icon")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHealthy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastHealthCheck")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PathPrefix")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PreserveHostHeader")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProxyPort")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RequireAuth")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RewriteUrls")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RewriteWebSocket")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("StripXFrameOptions")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Subdomain")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TimeoutSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsEnabled");

                    b.HasIndex("PathPrefix")
                        .IsUnique();

                    b.HasIndex("ProxyPort")
                        .IsUnique();

                    b.HasIndex("Subdomain")
                        .IsUnique();

                    b.ToTable("ProxyRoutes");
                });

            modelBuilder.Entity("Innovatek.Parallel.MiniCluster.Core.Entities.ProxySettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BaseDomainType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomBaseDomain")
                        .HasColumnType("TEXT");

                    b.Property<bool>("DefaultRequireAuth")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PortRangeEnd")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PortRangeStart")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServerIp")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ProxySettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseDomainType = "nip.io",
                            DefaultRequireAuth = true,
                            PortRangeEnd = 5099,
                            PortRangeStart = 5001,
                            UpdatedAt = new DateTime(2026, 2, 7, 12, 18, 29, 50, DateTimeKind.Utc).AddTicks(9083)
                        });
                });

            modelBuilder.Entity("Innovatek.Parallel.MiniCluster.Core.Entities.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccessLink")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AppId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Arguments")
                        .HasColumnType("TEXT");

                    b.Property<bool>("AutoStart")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CaptureOutput")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CreateNoWindow")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("EnvironmentVariables")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecutablePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("HealthCheckFailureThreshold")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HealthCheckGracePeriodSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HealthCheckIntervalSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HealthCheckTarget")
                        .HasColumnType("TEXT");

                    b.Property<int>("HealthCheckTimeoutSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HealthCheckType")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsExternal")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("MachineId")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxRestartDelaySeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxRestarts")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RestartDelaySeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RestartPolicy")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RestartWindowSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ServiceType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("UseExponentialBackoff")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseShellExecute")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WorkingDirectory")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AppId");

                    b.HasIndex("AutoStart");

                    b.HasIndex("MachineId");

                    b.HasIndex("Name");

                    b.HasIndex("AppId", "Name")
                        .IsUnique();

                    b.HasIndex("AppId", "Slug")
                        .IsUnique();

                    b.ToTable("ControlledApps", (string)null);
                });

            modelBuilder.Entity("Innovatek.Parallel.MiniCluster.Core.Entities.ServiceFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.ToTable("AppFiles", (string)null);
                });

            modelBuilder.Entity("Innovatek.Parallel.MiniCluster.Core.Entities.ServiceGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ParentGroupId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("ParentGroupId");

                    b.ToTable("AppGroups", (string)null);
                });

            modelBuilder.Entity("Innovatek.Parallel.MiniCluster.Core.Entities.ServiceGroupAssignment", b =>
                {
                    b.Property<Guid>("ServiceId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("ServiceId", "GroupId");

                    b.HasIndex("GroupId");

                    b.ToTable("AppGroupAssignments", (string)null);
                });

            modelBuilder.Entity("Innovatek.Parallel.MiniCluster.Core.Entities.ServiceVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConfigDiff")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigSnapshot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeployedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DeployedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeploymentNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("DeploymentStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GitBranch")
                        .HasColumnType("TEXT");

                    b.Property<string>("GitCommit")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("GitMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RolledBackAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.HasIndex("ServiceId", "SequenceNumber")
                        .IsUnique();

                    b.ToTable("ServiceVersions", (string)null);
                });

            modelBuilder.Entity("Innovatek.Parallel.Identity.Entities.RefreshToken", b =>
                {
                    b.HasOne("Innovatek.Parallel.Identity.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Innovatek.Parallel.MiniCluster.Core.Entities.App", b =>
                {
                    b.HasOne("Innovatek.Parallel.MiniCluster.Core.Entities.App", "ParentApp")
                        .WithMany("ChildApps")
                        .HasForeignKey("ParentAppId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentApp");
                });

            modelBuilder.Entity("Innovatek.Parallel.MiniCluster.Core.Entities.AppSnapshot", b =>
                {
                    b.HasOne("Innovatek.Parallel.MiniCluster.Core.Entities.App", "App")
                        .WithMany()
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("App");
                });

            modelBuilder.Entity("Innovatek.Parallel.MiniCluster.Core.Entities.AppSnapshotEntry", b =>
                {
                    b.HasOne("Innovatek.Parallel.MiniCluster.Core.Entities.AppSnapshot", "AppSnapshot")
                        .WithMany("Entries")
                        .HasForeignKey("AppSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Innovatek.Parallel.MiniCluster.Core.Entities.ServiceVersion", "ServiceVersion")
                        .WithMany()
                        .HasForeignKey("ServiceVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppSnapshot");

                    b.Navigation("ServiceVersion");
                });

            modelBuilder.Entity("Innovatek.Parallel.MiniCluster.Core.Entities.ContainerConfig", b =>
                {
                    b.HasOne("Innovatek.Parallel.MiniCluster.Core.Entities.Service", "Service")
                        .WithOne("ContainerConfig")
                        .HasForeignKey("Innovatek.Parallel.MiniCluster.Core.Entities.ContainerConfig", "ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Innovatek.Parallel.MiniCluster.Core.Entities.CronJob", b =>
                {
                    b.HasOne("Innovatek.Parallel.MiniCluster.Core.Entities.App", "App")
                        .WithMany()
                        .HasForeignKey("AppId");

                    b.HasOne("Innovatek.Parallel.MiniCluster.Core.Entities.CronJob", "DependsOnJob")
                        .WithMany()
                        .HasForeignKey("DependsOnJobId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Innovatek.Parallel.MiniCluster.Core.Entities.ServiceGroup", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId");

                    b.HasOne("Innovatek.Parallel.MiniCluster.Core.Entities.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId");

                    b.Navigation("App");

                    b.Navigation("DependsOnJob");

                    b.Navigation("Group");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Innovatek.Parallel.MiniCluster.Core.Entities.CronJobRun", b =>
                {
                    b.HasOne("Innovatek.Parallel.MiniCluster.Core.Entities.CronJob", null)
                        .WithMany("Runs")
                        .HasForeignKey("CronJobId");

                    b.HasOne("Innovatek.Parallel.MiniCluster.Core.Entities.CronJob", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("Innovatek.Parallel.MiniCluster.Core.Entities.DeploymentConfig", b =>
                {
                    b.HasOne("Innovatek.Parallel.MiniCluster.Core.Entities.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Innovatek.Parallel.MiniCluster.Core.Entities.GroupVariable", b =>
                {
                    b.HasOne("Innovatek.Parallel.MiniCluster.Core.Entities.ServiceGroup", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Innovatek.Parallel.MiniCluster.Core.Entities.Service", b =>
                {
                    b.HasOne("Innovatek.Parallel.MiniCluster.Core.Entities.App", "App")
                        .WithMany("Services")
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Innovatek.Parallel.MiniCluster.Core.Entities.Machine", null)
                        .WithMany("Services")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("App");
                });

            modelBuilder.Entity("Innovatek.Parallel.MiniCluster.Core.Entities.ServiceGroup", b =>
                {
                    b.HasOne("Innovatek.Parallel.MiniCluster.Core.Entities.ServiceGroup", "ParentGroup")
                        .WithMany("ChildGroups")
                        .HasForeignKey("ParentGroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentGroup");
                });

            modelBuilder.Entity("Innovatek.Parallel.MiniCluster.Core.Entities.ServiceGroupAssignment", b =>
                {
                    b.HasOne("Innovatek.Parallel.MiniCluster.Core.Entities.ServiceGroup", "Group")
                        .WithMany("ServiceAssignments")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Innovatek.Parallel.MiniCluster.Core.Entities.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Innovatek.Parallel.MiniCluster.Core.Entities.ServiceVersion", b =>
                {
                    b.HasOne("Innovatek.Parallel.MiniCluster.Core.Entities.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Innovatek.Parallel.Identity.Entities.User", b =>
                {
                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("Innovatek.Parallel.MiniCluster.Core.Entities.App", b =>
                {
                    b.Navigation("ChildApps");

                    b.Navigation("Services");
                });

            modelBuilder.Entity("Innovatek.Parallel.MiniCluster.Core.Entities.AlertEvent", b =>
                {
                    b.HasOne("Innovatek.Parallel.MiniCluster.Core.Entities.AlertRule", "AlertRule")
                        .WithMany()
                        .HasForeignKey("AlertRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlertRule");
                });

            modelBuilder.Entity("Innovatek.Parallel.MiniCluster.Core.Entities.AppSnapshot", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("Innovatek.Parallel.MiniCluster.Core.Entities.CronJob", b =>
                {
                    b.Navigation("Runs");
                });

            modelBuilder.Entity("Innovatek.Parallel.MiniCluster.Core.Entities.Machine", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("Innovatek.Parallel.MiniCluster.Core.Entities.Service", b =>
                {
                    b.Navigation("ContainerConfig");
                });

            modelBuilder.Entity("Innovatek.Parallel.MiniCluster.Core.Entities.ServiceGroup", b =>
                {
                    b.Navigation("ChildGroups");

                    b.Navigation("ServiceAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
