// <auto-generated />
using System;
using Innovatek.Parallel.MiniCluster.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Innovatek.Parallel.MiniCluster.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Innovatek.Parallel.Identity.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReplacedByToken")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Innovatek.Parallel.Identity.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Operator");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Innovatek.Parallel.MiniCluster.Core.Entities.App", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("SortOrder");

                    b.ToTable("Apps");
                });

            modelBuilder.Entity("Innovatek.Parallel.MiniCluster.Core.Entities.AppSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableLogSearch")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxMessagesToKeepInUi")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MetricsAggregationIntervalSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MetricsCollectionIntervalSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MetricsRetentionHours")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AppSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EnableLogSearch = true,
                            MaxMessagesToKeepInUi = 1000,
                            MetricsAggregationIntervalSeconds = 60,
                            MetricsCollectionIntervalSeconds = 5,
                            MetricsRetentionHours = 24,
                            ModifiedAt = new DateTime(2026, 2, 5, 17, 36, 49, 623, DateTimeKind.Utc).AddTicks(4831)
                        });
                });

            modelBuilder.Entity("Innovatek.Parallel.MiniCluster.Core.Entities.Environment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Variables")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Environments");
                });

            modelBuilder.Entity("Innovatek.Parallel.MiniCluster.Core.Entities.GroupVariable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSecret")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GroupId", "Key")
                        .IsUnique();

                    b.ToTable("GroupVariables");
                });

            modelBuilder.Entity("Innovatek.Parallel.MiniCluster.Core.Entities.ProxyRoute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AllowedRoles")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiKey")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomHeaders")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EnableIframe")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnablePathPrefix")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnablePort")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableSubdomain")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Icon")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHealthy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastHealthCheck")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PathPrefix")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PreserveHostHeader")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProxyPort")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RequireAuth")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RewriteUrls")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RewriteWebSocket")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("StripXFrameOptions")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Subdomain")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TimeoutSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsEnabled");

                    b.HasIndex("PathPrefix")
                        .IsUnique();

                    b.HasIndex("ProxyPort")
                        .IsUnique();

                    b.HasIndex("Subdomain")
                        .IsUnique();

                    b.ToTable("ProxyRoutes");
                });

            modelBuilder.Entity("Innovatek.Parallel.MiniCluster.Core.Entities.ProxySettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BaseDomainType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomBaseDomain")
                        .HasColumnType("TEXT");

                    b.Property<bool>("DefaultRequireAuth")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PortRangeEnd")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PortRangeStart")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServerIp")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ProxySettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseDomainType = "nip.io",
                            DefaultRequireAuth = true,
                            PortRangeEnd = 5099,
                            PortRangeStart = 5001,
                            UpdatedAt = new DateTime(2026, 2, 5, 17, 36, 49, 631, DateTimeKind.Utc).AddTicks(4890)
                        });
                });

            modelBuilder.Entity("Innovatek.Parallel.MiniCluster.Core.Entities.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccessLink")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AppId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Arguments")
                        .HasColumnType("TEXT");

                    b.Property<bool>("AutoStart")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CaptureOutput")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CreateNoWindow")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("EnvironmentVariables")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecutablePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsExternal")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("UseShellExecute")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WorkingDirectory")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AppId");

                    b.HasIndex("AutoStart");

                    b.HasIndex("Name");

                    b.HasIndex("AppId", "Name")
                        .IsUnique();

                    b.HasIndex("AppId", "Slug")
                        .IsUnique();

                    b.ToTable("ControlledApps", (string)null);
                });

            modelBuilder.Entity("Innovatek.Parallel.MiniCluster.Core.Entities.ServiceFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.ToTable("AppFiles", (string)null);
                });

            modelBuilder.Entity("Innovatek.Parallel.MiniCluster.Core.Entities.ServiceGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ParentGroupId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("ParentGroupId");

                    b.ToTable("AppGroups", (string)null);
                });

            modelBuilder.Entity("Innovatek.Parallel.MiniCluster.Core.Entities.ServiceGroupAssignment", b =>
                {
                    b.Property<Guid>("ServiceId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("ServiceId", "GroupId");

                    b.HasIndex("GroupId");

                    b.ToTable("AppGroupAssignments", (string)null);
                });

            modelBuilder.Entity("Innovatek.Parallel.Identity.Entities.RefreshToken", b =>
                {
                    b.HasOne("Innovatek.Parallel.Identity.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Innovatek.Parallel.MiniCluster.Core.Entities.GroupVariable", b =>
                {
                    b.HasOne("Innovatek.Parallel.MiniCluster.Core.Entities.ServiceGroup", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Innovatek.Parallel.MiniCluster.Core.Entities.Service", b =>
                {
                    b.HasOne("Innovatek.Parallel.MiniCluster.Core.Entities.App", "App")
                        .WithMany("Services")
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("App");
                });

            modelBuilder.Entity("Innovatek.Parallel.MiniCluster.Core.Entities.ServiceGroup", b =>
                {
                    b.HasOne("Innovatek.Parallel.MiniCluster.Core.Entities.ServiceGroup", "ParentGroup")
                        .WithMany("ChildGroups")
                        .HasForeignKey("ParentGroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentGroup");
                });

            modelBuilder.Entity("Innovatek.Parallel.MiniCluster.Core.Entities.ServiceGroupAssignment", b =>
                {
                    b.HasOne("Innovatek.Parallel.MiniCluster.Core.Entities.ServiceGroup", "Group")
                        .WithMany("ServiceAssignments")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Innovatek.Parallel.MiniCluster.Core.Entities.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Innovatek.Parallel.Identity.Entities.User", b =>
                {
                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("Innovatek.Parallel.MiniCluster.Core.Entities.App", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("Innovatek.Parallel.MiniCluster.Core.Entities.ServiceGroup", b =>
                {
                    b.Navigation("ChildGroups");

                    b.Navigation("ServiceAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
